### ISSUE TITLE
MineTogether crash before main menu.

### ISSUE THREAD

**Issue by Moleculor** [FTBTeam/FTB-Presents-Direwolf20-1.16#1]
* **Modpack Version**: v1.0

* **Issue**: Pack crashes before reaching the main menu. Issue seems related to MineTogether and _possibly_ https://github.com/CreeperHost/MineTogether/issues/234.

* **Link to Log or Crash File Paste**: https://gist.github.com/Moleculor/7fd3455ee994816db8431c40d9a95543

* **Is it Repeatable?**: Yes. Two launches so far, two crashes, both complaining about MineTogether.

* **Mod/s Affected**: MineTogether-1.16.4-4.1.6RC3

* **Known Fix**: Probably related to me trying to use JDK14. Temporary workaround right now is to downgrade to... bleh... _Java8_. \*shudder\*

**Comment by Sunekaer** [comment]
https://github.com/CreeperHost/MineTogether/issues/422

**Comment by IamStig** [comment]
I also had a crash today due to MineTogether, but for me it crashed the game when I slept. I have been playing the pack since release day and thought my crash may have been because I updated some mods .... and added 2.
Updated Envirotech (added Envirocore), FTB Chunks, rsgauges, Pneumaticcraft, RFTools Storage, Industrial Forgoing & Extreme Reactors2. Also updated relevant core mods
Added Create and notenoughwands. 
I removed MineTogether and have had no further issues
