### ISSUE TITLE
World crash while updating from 1.2.0 to 1.3.1

### ISSUE THREAD

**Issue by M4RC0Sx** [FTBTeam/FTB-Presents-Direwolf20-1.16#109]
* **Modpack Version**: 1.3.1

* **Issue**: After upgrading from version 1.2.0, my world crashes while loading.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/0c65085e

* **Is it Repeatable?**: Yes, everytime I upgrade it to 1.3.1 from 1.2.0, my world crashes.

**Comment by bk-one** [comment]
+1, but with a different crash log: https://gist.github.com/bk-one/1023b070a43a9ac4e29ae284a1ed4f41

Repeatable on two machines with a fresh FTB Launcher install

**Comment by YonahBerthels** [comment]
I have exactly the same problem. After I updated from 1.2.0 to 1.3.1, I cant load any of my worlds.
However when I play on a server it works just fine.  
I have been looking for a way to fix this issue for many hours, but without any success. 
I looked into the crash reports for a bit, and they say: "exception ticking world". After I looked this up online, I read that this means that the save is corrupted, and there is no way to fix this. 
Since we have exactly the same problem, I fear your save has also been damaged beyond repair.

**Comment by bk-one** [comment]
I can still load my save on 1.2 though

**Comment by Dutchs** [comment]
Remove Optifine or update it to G6 pre12
[Optifine Issue #5197](https://github.com/sp614x/optifine/issues/5197)

**Comment by YonahBerthels** [comment]
I got it working by downgrading the version of Forge. It automatically select the one ending on 1.36, but I just needed to go to installation and then change it to the version ending on 1.15 and everything was fine.
