### ISSUE TITLE
"connection closed - mismatched mod channel list"

### ISSUE THREAD

**Issue by JTuckerr** [FTBTeam/FTB-Presents-Direwolf20-1.16#168]
* **Modpack Version**: 
direwolf20 1.16 v1.5.1

* **Issue**: 
Trying to connect to a server and failing - was able to connect to the same server before the update today but now cannot.
Tried to downgrade back to previous patch but can't, other people still connecting

* **Link to Log or Crash File Paste**: 
don't have

* **Is it Repeatable?**: 
yes
![Capture](https://user-images.githubusercontent.com/38744362/106253402-2b240f80-6263-11eb-8452-60c08d90effa.PNG)
![Capture1](https://user-images.githubusercontent.com/38744362/106253406-2c553c80-6263-11eb-8f54-6abc5b9782c6.PNG)

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Snappiestjack** [comment]
> * Trying to connect to a server and failing - was able to connect to the same server before the update today but now cannot.
>   Tried to downgrade back to previous patch but can't, other people still connecting

I'd say the server hasn't updated yet. Why can't you downgrade?

**Comment by JTuckerr** [comment]
> > * Trying to connect to a server and failing - was able to connect to the same server before the update today but now cannot.
> >   Tried to downgrade back to previous patch but can't, other people still connecting
> 
> I'd say the server hasn't updated yet. Why can't you downgrade?

Apologies, I didn't reread well enough apparently. What I meant to say is that I tried downgrading and that didn't fix the issue

**Comment by sadovsf** [comment]
Maybe server disabled some mods by hand (i had to do this because of broken Blood magic). In such case you would not be able to connect although versions would be same. Can you contact server owner? I play on 1.5.1 as well no issues (with that disabled blood magic i did on our server)

**Comment by crbnsmmrs** [comment]
I had the same issue when upgrading from 1.5.0 to 1.5.1 on 4 different computers (whole family plays). The issue is client side. The update script leaves behind older versions of mods. I removed 48 older versions of mods still in the pack and a couple that are no longer in the pack.

Fastest way to fix is to backup worlds, delete mod in FTB Launcher, (I also deleted the folder of that instance in the "Instance" folder), and reinstall 1.5.1.

absentbydesign-1.16.4-1.3.1.jar
appliedenergistics2-8.2.0-beta.2.jar
architectury-1.3.81-forge.jar
ars_nouveau-1.16.4-1.10.6.jar
BloodMagic-1.16.3-3.0.5-10.jar
Botania-1.16.4-410.jar
chiselsandbits-0.2.9-RELEASE.jar
CodeChickenLib-1.16.4-3.5.0.401-universal.jar
culinaryconstruct-forge-1.16.4-4.0.0.2.jar
Cyclic-1.16.4-1.1.3.jar
DarkUtilities-1.16.4-7.0.7.jar
DataFixerSlayer 1.0-3.jar
elevatorid-1.16.4-1.7.10.jar
emojiful-1.16.4-2.1.2.jar
EnderStorage-1.16.4-2.7.0.161-universal.jar
entangled-1.2.9-mc1.16.4.jar
ExtraStorage-1.16.4-1.2.2.jar
extremeSoundMuffler-3.5_Forge-1.16.4.jar
FastFurnace-1.16.3-4.3.0.jar
FastWorkbench-1.16.3-4.4.1.jar
FluxNetworks-1.16.4-6.1.5.10.jar
forge-1.16.4-geckolib-3.0.0.jar
ftb-janitor-1604.1.0.17.jar
itemcollectors-1.0.9-mc1.16.4.jar
JAMD-1.1.4-beta+mc-1.16.4.jar
kubejs-1604.3.4.144-forge.jar
kubejs-ui-1604.1.0.12.jar
launchertray-1.0.jar
launchertray-progress-1.0.jar
mcw-bridges-1.0.4-mc1.16.4.jar
mcw-doors-1.0.1fix-mc1.16.4.jar
mcw-trapdors-1.0.0-mc1.16.4.jar
mcws-roofs-2.0.0-mc1.16.4.jar
minecolonies-0.13.566-ALPHA-universal.jar
modular-routers-1.16.4-7.3.0-47.jar
movingelevators-1.2.31a-mc1.16.4.jar
Placebo-1.16.3-4.3.3.jar
pneumaticcraft-repressurized-1.16.4-2.9.2-116.jar
Powah-1.16.4-2.3.8.jar
Psi-1.16-90.jar
rsgauges-1.16.4-1.2.7-b2.jar
simplemagnets-1.0.11-mc1.16.4.jar
SimplyJetpacks2-1.16.4-2.6.5.2.jar
StorageDrawers-1.16.3-8.2.1.jar
structurize-0.13.104-ALPHA-universal.jar
The_Undergarden-1.16.4-0.4.3.jar
Toast-Control-1.16.3-4.3.0.jar
TOOLKIT-2.0.0.jar

**Comment by Sunekaer** [comment]
Basically it mean you there is a different between mods on your client and server.
If the server removed mods you should still be able to join even tho it says that message.
Other reason could be that your on a different version than the server is
