### ISSUE TITLE
Environmental Tech Frequency modifier not crafting

### ISSUE THREAD

**Issue by memyselfandcj** [FTBTeam/FTB-Presents-Direwolf20-1.16#175]
Pack Version 1.5.1
Server: Yes
No modifications to the pack

When trying to craft ET Frequency modifier it is only crafting the beginning tier regardless of how they are crafted.
Tried different tiers of interconnects and it will only craft beginning tier.
Tried different assemblers and different interconnect recipes and none worked.
After some messing around with creative and changing around the different parts...the frequency modifier is the part that seems to be the issue. Using one that is spawned in seems to work and can be upgraded to any tier.

**Comment by Sunekaer** [comment]
please test with 1.6.0

**Comment by luchokoldo** [comment]
I have a workaround of that bug, idk if is fixed in 1.6.0 but before making the frequency modifier, place the null modifier in the world and break it, then you can craft it w/o problems, also if you have a frequency modifier w/o nbt, place it in the world and break it and use it in the assembler with a tier 1

**Comment by memyselfandcj** [comment]
So this seems to be fine in 1.6.1. I was able to craft the different tiers...or at least the tiers that I can make for now. Will close this out.
