### ISSUE TITLE
Multiplayer Menu shows Red X on Server

### ISSUE THREAD

**Issue by TechyShishy** [FTBTeam/FTB-Presents-Direwolf20-1.16#215]
* **Modpack Version**: 1.6.1

* **Issue**:

  When attempting to connect to my multiplayer server, the game displays a red X next to it, indicating that there's a mod mismatch between client and server:
![Screenshot 2021-02-14 183138](https://user-images.githubusercontent.com/848519/107899351-e18a2480-6ef2-11eb-8d78-4a9c67f66e18.png)

  Digging into the logs, it looks like launchertray and MouseTweaks are only included in the client modset, and not in the server modset.  This makes sense, since they're both client-only mods, but forge doesn't like the mismatch.  If I actually attempt to connect to the server, everything works fine.

  I attempted to add both mods to the server in order to resolve the issue, and while that does fix it for me, it doesn't fix the problem for another user, who is on MacOS.  Apparently launchertray is a Windows specific mod.  If I remove launchertray from the server, it fixes it for that user, but breaks it again for me.

* **Link to Log or Crash File Paste**:
  * [Server latest.log](https://paste.feed-the-beast.com/view/9aad65d8)
  * [Server debug.log](https://paste.feed-the-beast.com/view/95d5db2c) 
  * [Server installer.log](https://paste.feed-the-beast.com/view/f468ec90) 
  * [Client latest.log](https://paste.feed-the-beast.com/view/26be5325) 
  * [Client debug.log](https://paste.feed-the-beast.com/view/d508a113)

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: launchertray, MouseTweaks

* **Known Fix**:  None

**Comment by JoJoDeveloping** [comment]
Forge is nice and tells you which mods are [naughty](https://mcforge.readthedocs.io/en/1.15.x/concepts/sides/#writing-one-sided-mods) -- see client debug.log line 529:
```
[14Feb2021 18:44:39.264] [Netty Client IO #0/INFO] [net.minecraftforge.fml.client.ClientHooks/CLIENTHOOKS]: Client has mods that are missing on server: [traylauncher, mousetweaks]
```

For mousetweaks, that bug is already fixed in the latest version: https://github.com/YaLTeR/MouseTweaks/issues/45, the modpack just needs to be updated.

As for launcher tray, IDK I'm on Linux, and I can't find that mod anywhere. It's not even in the mod list: https://feed-the-beast.com/modpack/ftb_presents_direwolf20_1_16. Do you have a GitHub repo, a CurseForge/FTB download? The key is finding out who made that mod because only they can fix it.

**Comment by TechyShishy** [comment]
Yup, that line is how I figured out which mods were the problem in the first place.

LauncherTray is apparently something Windows specific designed to hide the game window while loading and redirect loading progress into the FTB App application itself.

**Comment by EliManthey** [comment]
I am having this issue as well. has there been a solution for this found? Another thing to note for us is that of the 4 people attempting to join only 2 of us had this issue. all 4 of us downloaded the ftblauncher app and the direwolf20 pack on the same night.

**Comment by JoJoDeveloping** [comment]
The solution is
1) update mousetweaks
2) do not use the FTB Launcher on windows because it pulls a malware move and forces that other mod onto you. Use another OS or another launcher.

**Comment by EliManthey** [comment]
Is there a different launcher we can download the pack from?

**Comment by deltacomc** [comment]
You can use MultiMC in Dev-Mode

![grafik](https://user-images.githubusercontent.com/70367817/108735943-64cdfa80-7531-11eb-8b95-f32121256fc1.png)

You can than add FTB specific instances

![grafik](https://user-images.githubusercontent.com/70367817/108736146-a068c480-7531-11eb-950f-ff151e1abae7.png)


> Is there a different launcher we can download the pack from?

**Comment by Quetzi** [comment]
The Traylauncher mod that is added when launching using the FTB App is not 'malware' it's job is to stop the game rendering and to send log messages from the Minecraft client to the App. By doing this not only does it allow us to display ads during the loading phase it also drastically reduces the loading time of the game because the process of rendering the loading window has a large impact on overall load times. While it may be closed and only available internally right now, the intention is that this will be made available to everyone to use as the load time reductions are something that we shouldn't reserve for ourselves. 

Forge has changed the way mods mark themselves as client or server only and that is why the red x shows up when it shouldn't, the team know about this one and will hopefully have it fixed soon.

**Comment by Sunekaer** [comment]
Should be fixed
