### ISSUE TITLE
Create copper ore not usable

### ISSUE THREAD

**Issue by detsuo04** [FTBTeam/FTB-Presents-Direwolf20-1.16#255]
installed a the new direwolf pack yesterday and today I have encountered create copper ore in the overworld, however it is not in NEI and I can't smelt it in a furnace.
![2021-04-13_14 30 23](https://user-images.githubusercontent.com/77883366/114609996-0ab20180-9c65-11eb-80f5-ce6b09fab390.png)

**Comment by BeefyGames** [comment]
The same goes for the Mekanism copper ore. Cannot find it anywhere, but instead of the furnace, it will not go into the pulverized at all or even be placed in the applied energetics ore doubler. Having it into a chest to draw it from does not work either. It just seems to not want to be used at all for anything... there is no crafting recipe in JEI for it either. Nothing you can use the ore with, useless.

**Comment by Sunekaer** [comment]
Is this on server or sp? because your not meant to be able to get these ores

**Comment by BeefyGames** [comment]
Its In SP. However, I found the create ore naturally in the world, but entered creative mode to substitute it with another wore (the one from mekasim) as neither of them served any purpose and worked, where I could not ore double or smelt them in any way at all.

**Comment by Sunekaer** [comment]
hmm you wasn't meant to be able to get that ore in the world.. weird, ill tweak the script a bit so they work also

**Comment by Sunekaer** [comment]
Try with the newest version

**Comment by grekiki** [comment]
Smeltable now, solved for me.
