### ISSUE TITLE
Memory leak in 1.2.0 anyone else

### ISSUE THREAD

**Issue by robertm1771** [FTBTeam/FTB-Presents-Direwolf20-1.16#65]
* **Modpack Version**: 1.2.0
* 
* **Issue**: If I stay at my base seem ok for hours. But if I go to my mekanism reactor/turbine area or explorer the world much at all. I will start getting freezing as memory start to push up to 95% every 20 seconds or so.

* **Is it Repeatable?**: I can see this in my world over 5 to 6 restarts instance

Seems loading chucks as I move around started the problem. Other dims or current.  
I didn't seem this problem before 1.2.0 downgrading seemed to resolve.

Maybe others will have more insight to issue.

**Comment by TheDarkPreacher** [comment]
Server Pack Version: 1.2.0

Seem to be having a memory leak issue on server as well. Console keeps getting spammed with "Can't keep up! Is the server overloaded? Running 8340ms or 166 ticks behind" and the times all hover around 8Kms or 160 ticks behind. Also get console messages of "Player moved too quickly!" and reports of rubberbanding from players. Also had a player lose connection due to "Internal Exception: io.netty.handler.codec.EncoderException: java.lang.OutOfMemoryError: Java heap space". Server never crashes, just keep getting console spam. When the server is restarted, the problem goes away for about 20 minutes with one player online, but as soon as another player joins the server, the rubberbanding returns, the message spam in the console returns, and eventually someone loses connection due to OutOfMemoryError. Attached is the latest.log file.
[latest.log](https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/files/5758068/latest.log)

**Comment by Sunekaer** [comment]
How much memory are you giving it?
How many players?
Server or SP?

**Comment by TheDarkPreacher** [comment]
Server is getting 4GB, only had 3 players max on the server right now. Added Dynamic View to the server, and pregenned an area with a radius of 150 chunks and that seems to have helped some. Dynamic view is set to 12 max, 4 min, refresh rate of 43. Admittedly, this is just some hacky bandaid work, but at least the CPU usage isn't looking like the readout of an ECG during a heart attack. Had multiple spikes of over 100% CPU usage on the server before I did that.

**Comment by Sunekaer** [comment]
4gb does seems a bit low for this pack.
Minecraft is be coming more and more heavy with each version

**Comment by robertm1771** [comment]
For me 6gb memory running SP.  Giving more memory doesn't help for long. 

Found the log thought I lost it..
https://paste.feed-the-beast.com/view/f80f0e06

**Comment by Sunekaer** [comment]
> For me 6gb memory running SP. Giving more memory doesn't help for long.
> 
> Found the log thought I lost it..
> https://paste.feed-the-beast.com/view/f80f0e06

Thats different because that's on client

**Comment by robertm1771** [comment]
> > For me 6gb memory running SP. Giving more memory doesn't help for long.
> > Found the log thought I lost it..
> > https://paste.feed-the-beast.com/view/f80f0e06
> 
> Thats different because that's on client

Yea understood just given as much info as I can.

**Comment by Sunekaer** [comment]
> > > For me 6gb memory running SP. Giving more memory doesn't help for long.
> > > Found the log thought I lost it..
> > > https://paste.feed-the-beast.com/view/f80f0e06
> > 
> > 
> > Thats different because that's on client
> 
> Yea understood just given as much info as I can.

look at the pinned issue, those args would help you

**Comment by robertm1771** [comment]
> > > > For me 6gb memory running SP. Giving more memory doesn't help for long.
> > > > Found the log thought I lost it..
> > > > https://paste.feed-the-beast.com/view/f80f0e06
> > > 
> > > 
> > > Thats different because that's on client
> > 
> > 
> > Yea understood just given as much info as I can.
> 
> look at the pinned issue, those args would help you

These augs do seem to help thanks. I saw that pinned issue didn't seem relevant to me at the time. Anyone else having issues should try them as well..

**Comment by rbplayslinux** [comment]
Definitely something going on with my server. Usually within a few hours of restart ram is absolutely pegged at the maximum. 


![Screenshot from 2021-01-03 22-06-59](https://user-images.githubusercontent.com/57599141/103497870-dc748880-4e10-11eb-9636-31134a36bf25.png)
